name: Setup GitHub Actions Bot
description: Configures Git user.name and user.email for GitHub Actions, allowing commits and other Git operations to be attributed correctly.

runs:
  using: composite
  steps:
    - name: Configure Git User
      shell: bash
      run: |
        git config --global user.name  'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

branding:
  icon: terminal
  color: yellow
